"""Add status field to hotels

Revision ID: 02248baf09fd
Revises: 3865cdca3636
Create Date: 2026-01-20 07:59:22.757802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02248baf09fd'
down_revision: Union[str, None] = '3865cdca3636'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotels', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hotels', 'status')
    # ### end Alembic commands ###
